### ISSUE TITLE
How to add this in a SwiftUI View?

### ISSUE THREAD

**Issue by alejandroxin93** [EthanLipnik/MeshKit#2]
I'm sorry, I'm new to swift and I really tried to rewrite this into SwiftUI, but failed..
Hope you can provide a SwiftUI guide. Thank you very much!!

**Comment by EthanLipnik** [comment]
> I'm sorry, I'm new to swift and I really tried to rewrite this into SwiftUI, but failed..
> 
> Hope you can provide a SwiftUI guide. Thank you very much!!

Hey! You can use `UIViewRepresentable` to bring it to SwiftUI. [Here's a great guide for it.](https://www.hackingwithswift.com/quick-start/swiftui/how-to-wrap-a-custom-uiview-for-swiftui)

If you use MeshKit's `feature/mesh-gradient-integration` branch it has native SwiftUI support but no documentation yet (also has more features and better quality)

**Comment by alejandroxin93** [comment]
Hi! Thank you for reply! I tried "feature/mesh-gradient-integration" this time and it works perfect! Thanks a lot, great work!!!
